//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBO.reporteCitasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", ConfigurationName="reporteCitasWS.ReporteCitasWS")]
    public interface ReporteCitasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/ReporteCitasWS/ReporteDeCitasGeneralRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/ReporteCitasWS/ReporteDeCitasGeneralResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse ReporteDeCitasGeneral(SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softcitws.soft.pucp.edu.pe/ReporteCitasWS/ReporteDeCitasGeneralRequest", ReplyAction="http://softcitws.soft.pucp.edu.pe/ReporteCitasWS/ReporteDeCitasGeneralResponse")]
        System.Threading.Tasks.Task<SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse> ReporteDeCitasGeneralAsync(SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/")]
    public partial class reporteCitaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codMedicoField;
        
        private string doctorField;
        
        private string especialidadField;
        
        private string fechaCitaField;
        
        private string horaField;
        
        private string idCitaField;
        
        private string pacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codMedico {
            get {
                return this.codMedicoField;
            }
            set {
                this.codMedicoField = value;
                this.RaisePropertyChanged("codMedico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string doctor {
            get {
                return this.doctorField;
            }
            set {
                this.doctorField = value;
                this.RaisePropertyChanged("doctor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaCita {
            get {
                return this.fechaCitaField;
            }
            set {
                this.fechaCitaField = value;
                this.RaisePropertyChanged("fechaCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string idCita {
            get {
                return this.idCitaField;
            }
            set {
                this.idCitaField = value;
                this.RaisePropertyChanged("idCita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
                this.RaisePropertyChanged("paciente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReporteDeCitasGeneral", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ReporteDeCitasGeneralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codMedico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_fini;
        
        public ReporteDeCitasGeneralRequest() {
        }
        
        public ReporteDeCitasGeneralRequest(int idEspecialidad, int codMedico, string fecha_inicio, string fecha_fini) {
            this.idEspecialidad = idEspecialidad;
            this.codMedico = codMedico;
            this.fecha_inicio = fecha_inicio;
            this.fecha_fini = fecha_fini;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReporteDeCitasGeneralResponse", WrapperNamespace="http://softcitws.soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ReporteDeCitasGeneralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softcitws.soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftBO.reporteCitasWS.reporteCitaDTO[] @return;
        
        public ReporteDeCitasGeneralResponse() {
        }
        
        public ReporteDeCitasGeneralResponse(SoftBO.reporteCitasWS.reporteCitaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteCitasWSChannel : SoftBO.reporteCitasWS.ReporteCitasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteCitasWSClient : System.ServiceModel.ClientBase<SoftBO.reporteCitasWS.ReporteCitasWS>, SoftBO.reporteCitasWS.ReporteCitasWS {
        
        public ReporteCitasWSClient() {
        }
        
        public ReporteCitasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteCitasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteCitasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteCitasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse SoftBO.reporteCitasWS.ReporteCitasWS.ReporteDeCitasGeneral(SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest request) {
            return base.Channel.ReporteDeCitasGeneral(request);
        }
        
        public SoftBO.reporteCitasWS.reporteCitaDTO[] ReporteDeCitasGeneral(int idEspecialidad, int codMedico, string fecha_inicio, string fecha_fini) {
            SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest inValue = new SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.codMedico = codMedico;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_fini = fecha_fini;
            SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse retVal = ((SoftBO.reporteCitasWS.ReporteCitasWS)(this)).ReporteDeCitasGeneral(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse> SoftBO.reporteCitasWS.ReporteCitasWS.ReporteDeCitasGeneralAsync(SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest request) {
            return base.Channel.ReporteDeCitasGeneralAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBO.reporteCitasWS.ReporteDeCitasGeneralResponse> ReporteDeCitasGeneralAsync(int idEspecialidad, int codMedico, string fecha_inicio, string fecha_fini) {
            SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest inValue = new SoftBO.reporteCitasWS.ReporteDeCitasGeneralRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.codMedico = codMedico;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_fini = fecha_fini;
            return ((SoftBO.reporteCitasWS.ReporteCitasWS)(this)).ReporteDeCitasGeneralAsync(inValue);
        }
    }
}
